spring:
  datasource:
    url: jdbc:postgresql://dpg-cqhmv2d6l47c73fqic7g-a.singapore-postgres.render.com:5432/taskmanager_mtf4
    username: root
    password: E7i99iEmzVS55SqcOKifT9aNezYoIl1R
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
